/**
 * QR codes are generated at build time, never at runtime.
 *
 * The URLs are constants, the panel may be offline, and a QR that fails to
 * render is a dead end in a showroom. Emitting SVG path data into the bundle
 * removes the failure mode entirely.
 *
 *   npx tsx scripts/generate-qr.ts
 */
import QRCode from 'qrcode';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { CONTACT } from '../content/contact';

const OUT = path.join(process.cwd(), 'content', 'generated', 'qr.ts');

async function svg(url: string) {
  const raw = await QRCode.toString(url, {
    type: 'svg',
    errorCorrectionLevel: 'M',
    margin: 0,
    color: { dark: '#1A1815', light: '#00000000' },
  });
  return raw.replace(/\n/g, '').replace(/'/g, "\\'");
}

async function main() {
  await mkdir(path.dirname(OUT), { recursive: true });
  const primary = await svg(CONTACT.primaryUrl);
  const instagram = await svg(CONTACT.instagramUrl);
  await writeFile(
    OUT,
    `// GENERATED by scripts/generate-qr.ts — do not edit by hand.\n` +
      `export const QR_PRIMARY = '${primary}';\n` +
      `export const QR_INSTAGRAM = '${instagram}';\n`,
    'utf8',
  );
  process.stdout.write(`Wrote ${path.relative(process.cwd(), OUT)}\n`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
