/**
 * The world map on the Craft screen, baked to a path at build time.
 *
 * The panel is a kiosk that must work with the network down, and shipping a
 * projection library plus a TopoJSON file to draw one static outline is 200KB
 * of runtime to redraw the same shape on every load. So the shape is computed
 * once, here, and written to content/generated/map.ts as a plain string.
 *
 *   npm run map:generate
 *
 * Re-run it after adding a city to CITIES in content/reach.ts — the points are
 * projected from the same array the list is set from, so the two screens can
 * never disagree about where the studio has worked.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import * as topojson from 'topojson-client';
import { geoEquirectangular, geoPath } from 'd3-geo';
import { CITIES } from '../content/reach';

/** The drawing's own coordinate space. Scaled to the panel by the component. */
const WIDTH = 1080;
const HEIGHT = 560;

/*
 * The window the projection is fitted to. 66°N cuts above the northernmost
 * work and keeps Greenland from dominating the frame; -40°S sits below São
 * Paulo with room to breathe. Equirectangular rather than a curved projection
 * because this is a diagram of reach, not a navigation chart, and a rectangle
 * sits in a portrait composition without arguing with it.
 */
const WINDOW: GeoJSON.Polygon = {
  type: 'Polygon',
  coordinates: [[[-180, 66], [180, 66], [180, -40], [-180, -40], [-180, 66]]],
};

function main() {
  const atlas = JSON.parse(
    readFileSync(path.join(process.cwd(), 'node_modules/world-atlas/land-110m.json'), 'utf8'),
  );
  const land = topojson.feature(atlas, atlas.objects.land) as GeoJSON.Feature | GeoJSON.FeatureCollection;
  const features = 'features' in land ? land.features : [land];

  /*
   * Antarctica goes. The studio has never worked there, and at this projection
   * it is a white slab across the bottom of the frame — the loudest shape on a
   * screen whose whole point is nineteen quiet dots.
   */
  const rings: GeoJSON.Position[][][] = [];
  for (const feature of features) {
    const geometry = feature.geometry;
    const polygons =
      geometry.type === 'Polygon'
        ? [geometry.coordinates]
        : geometry.type === 'MultiPolygon'
          ? geometry.coordinates
          : [];
    for (const polygon of polygons) {
      if (Math.max(...polygon[0].map((point) => point[1])) < -55) continue;
      rings.push(polygon);
    }
  }

  const projection = geoEquirectangular().fitExtent([[0, 0], [WIDTH, HEIGHT]], WINDOW);
  const drawn = geoPath(projection)({ type: 'MultiPolygon', coordinates: rings });
  if (!drawn) throw new Error('the land outline projected to nothing');
  // Integer precision: the drawing is 1080 units wide and this halves the file.
  const outline = drawn.replace(/-?\d+\.\d+/g, (value) => String(Math.round(parseFloat(value))));

  const points = CITIES.map((city) => {
    const projected = projection([city.lon, city.lat]);
    if (!projected) throw new Error(`${city.name} does not project inside the window`);
    return { name: city.name, x: Math.round(projected[0]), y: Math.round(projected[1]) };
  });

  const file = `/* Generated by scripts/generate-map.ts. Do not edit — run \`npm run map:generate\`. */

export const MAP = {
  width: ${WIDTH},
  height: ${HEIGHT},
  /** Land outline, Antarctica removed, equirectangular. */
  land: '${outline}',
  /** One point per entry in CITIES, in the same order. */
  points: ${JSON.stringify(points)} as ReadonlyArray<{ name: string; x: number; y: number }>,
} as const;
`;
  const out = path.join(process.cwd(), 'content', 'generated', 'map.ts');
  writeFileSync(out, file);
  process.stdout.write(`${points.length} places, ${outline.length} path characters -> ${out}\n`);
}

main();
