/**
 * Placeholder media generator — REVIEW SCAFFOLDING, NOT ARTWORK.
 *
 * There is no photography in this repo yet. This emits deterministic, warm
 * gradient plates at the real master dimensions so type scale, reach bands and
 * scroll physics can be reviewed on the panel before the shoot lands. Every
 * plate is labelled so nobody mistakes one for a Viterbo interior.
 *
 * Replace by dropping real originals into `media-src/` and running
 * `npm run media:process` — the emitted metadata has the same shape.
 *
 *   npx tsx scripts/generate-placeholders.ts
 */
import sharp from 'sharp';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const OUT_DIR = path.join(process.cwd(), 'public', 'media', 'placeholder');
const MANIFEST = path.join(process.cwd(), 'content', 'generated', 'placeholder-media.ts');

type Plate = { key: string; label: string; shape: 'landscape' | 'portrait' | 'square' };

const DIMS = {
  landscape: [2160, 1440],
  portrait: [2160, 3840],
  square: [2160, 2160],
} as const;

/**
 * Warm interior-ish palettes, cycled so consecutive plates read differently.
 * Pitched light: these sit on a warm off-white ground, and dark plates would
 * misrepresent how real photography will weigh on the page.
 */
const PALETTES: Array<[string, string, string]> = [
  ['#8d7a63', '#c3b096', '#efe6d6'],
  ['#6f817a', '#a9bcb2', '#e2ece5'],
  ['#9a7466', '#cfa895', '#f3e2d6'],
  ['#6f7690', '#a8b0c8', '#e4e7f0'],
  ['#8f8058', '#ccbb8c', '#f2ead2'],
  ['#7d6a76', '#b6a2ae', '#ece2e8'],
];

function plateSvg(w: number, h: number, i: number, label: string) {
  const [a, b, c] = PALETTES[i % PALETTES.length];
  const angle = (i * 37) % 180;
  const fs = Math.round(w / 42);
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}">
  <defs>
    <linearGradient id="g" gradientTransform="rotate(${angle} 0.5 0.5)">
      <stop offset="0%" stop-color="${a}"/>
      <stop offset="55%" stop-color="${b}"/>
      <stop offset="100%" stop-color="${c}"/>
    </linearGradient>
    <radialGradient id="v" cx="50%" cy="42%" r="78%">
      <stop offset="55%" stop-color="#000" stop-opacity="0"/>
      <stop offset="100%" stop-color="#000" stop-opacity="0.22"/>
    </radialGradient>
  </defs>
  <rect width="${w}" height="${h}" fill="url(#g)"/>
  <rect x="${w * 0.08}" y="${h * 0.12}" width="${w * 0.34}" height="${h * 0.62}" fill="#000" opacity="0.07"/>
  <rect x="${w * 0.52}" y="${h * 0.3}" width="${w * 0.4}" height="${h * 0.5}" fill="#fff" opacity="0.16"/>
  <rect width="${w}" height="${h}" fill="url(#v)"/>
  <text x="${w * 0.06}" y="${h - h * 0.06}" font-family="Helvetica, Arial, sans-serif"
        font-size="${fs}" fill="#1a1815" fill-opacity="0.4" letter-spacing="${fs * 0.12}">
    PLACEHOLDER · ${label.toUpperCase()}
  </text>
</svg>`;
}

async function blurDataURL(buf: Buffer): Promise<string> {
  const tiny = await sharp(buf).resize(16, 16, { fit: 'inside' }).webp({ quality: 40 }).toBuffer();
  return `data:image/webp;base64,${tiny.toString('base64')}`;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  await mkdir(path.dirname(MANIFEST), { recursive: true });

  const plates: Plate[] = [];
  const PROJECTS = [
    'castilho-203', 'av-republica', 'cascais-seafront', 'chelsea',
    'singapore-penthouse', 'rio-de-janeiro', 'porto-villa', 'bangkok-estate',
    'lisbon-palace', 'hotel-albatroz', 'estoril-estate', 'tuscany-estate',
    'cabana-sass',
  ];
  PROJECTS.forEach((slug, i) => {
    // A handful of heroes genuinely have vertical composition (§4).
    plates.push({ key: `${slug}-hero`, label: slug, shape: i % 4 === 0 ? 'portrait' : 'landscape' });
    for (let g = 1; g <= 3; g += 1) {
      plates.push({ key: `${slug}-${g}`, label: `${slug} ${g}`, shape: g === 2 ? 'square' : 'landscape' });
    }
  });
  ['cascais', 'workshops', 'port-of-lisbon', 'in-transit', 'on-site'].forEach((k) =>
    plates.push({ key: `craft-${k}`, label: `craft ${k}`, shape: 'portrait' }),
  );

  const entries: string[] = [];
  for (const [i, plate] of plates.entries()) {
    const [w, h] = DIMS[plate.shape];
    const svg = Buffer.from(plateSvg(w, h, i, plate.label));
    const buf = await sharp(svg).webp({ quality: 72, effort: 4 }).toBuffer();
    const file = `${plate.key}.webp`;
    await writeFile(path.join(OUT_DIR, file), buf);
    const blur = await blurDataURL(buf);
    entries.push(
      `  '${plate.key}': { src: '/media/placeholder/${file}', width: ${w}, height: ${h}, ` +
        `aspect: '${plate.shape}', blurDataURL: '${blur}', ` +
        `alt: { en: 'Placeholder plate', pt: 'Imagem provisória' } },`,
    );
    process.stdout.write(`  ${file} ${(buf.byteLength / 1024).toFixed(0)}KB\n`);
  }

  await writeFile(
    MANIFEST,
    `// GENERATED by scripts/generate-placeholders.ts — do not edit by hand.\n` +
      `// Review scaffolding only. Real assets replace this via scripts/process-images.ts.\n` +
      `import type { Image } from '../types';\n\n` +
      `export const PLACEHOLDER: Record<string, Image> = {\n${entries.join('\n')}\n};\n\n` +
      `export function plate(key: string): Image {\n` +
      `  const found = PLACEHOLDER[key];\n` +
      `  if (!found) throw new Error(\`Unknown placeholder plate: \${key}\`);\n` +
      `  return found;\n}\n`,
    'utf8',
  );
  process.stdout.write(`\nWrote ${plates.length} plates and ${path.relative(process.cwd(), MANIFEST)}\n`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
